using Ingweland.Fog.Models.Hoh.Enums;

namespace Ingweland.Fog.Application.Core.Extensions;

public static class BuildingGroupExtensions
{
    public static string ToStringRepresentation(this BuildingGroup group)
    {
        return group switch
        {
            BuildingGroup.Alchemist => "alchemist",
            BuildingGroup.Artisan => "artisan",
            BuildingGroup.AverageAviary => "averageAviary",
            BuildingGroup.AverageBeehive => "averageBeehive",
            BuildingGroup.AverageCamelFarm => "averageCamelFarm",
            BuildingGroup.AverageGoldMine => "averageGoldMine",
            BuildingGroup.AverageHome => "averageHome",
            BuildingGroup.AverageMerchant => "averageMerchant",
            BuildingGroup.AveragePapyrusField => "averagePapyrusField",
            BuildingGroup.AveragePier => "averagePier",
            BuildingGroup.AverageRiceFarm => "averageRiceFarm",
            BuildingGroup.AverageRitualSite => "averageRitualSite",
            BuildingGroup.BeehiveRunestone => "beehiveRunestone",
            BuildingGroup.Carpenter => "carpenter",
            BuildingGroup.CarpetMaker => "carpetMaker",
            BuildingGroup.CavalryBarracks => "cavalryBarracks",
            BuildingGroup.CeremonyOutfitter => "ceremonyOutfitter",
            BuildingGroup.Channel => "channel",
            BuildingGroup.Chronicler => "chronicler",
            BuildingGroup.CityHall => "cityHall",
            BuildingGroup.ClayProcessor => "clayProcessor",
            BuildingGroup.CoffeeBrewer => "coffeeBrewer",
            BuildingGroup.CollectableAmphitheatre => "collectableAmphitheatre",
            BuildingGroup.CollectableArchitectsStudioV2 => "collectableArchitectsStudioV2",
            BuildingGroup.CollectableMinoanWatchtowerV2 => "collectableMinoanWatchtowerV2",
            BuildingGroup.CollectableSchoolV2 => "collectableSchoolV2",
            BuildingGroup.CompactCulture => "compactCulture",
            BuildingGroup.DomesticFarm => "domesticFarm",
            BuildingGroup.EvolvingFountainOfYouth => "evolvingFountainOfYouth",
            BuildingGroup.EvolvingGarden => "evolvingGarden",
            BuildingGroup.ExpeditionPier => "expeditionPier",
            BuildingGroup.ExpeditionPort => "expeditionPort",
            BuildingGroup.Fountain => "fountain",
            BuildingGroup.Furnace => "furnace",
            BuildingGroup.Glassblower => "glassblower",
            BuildingGroup.Goldsmith => "goldsmith",
            BuildingGroup.HeavyInfantryBarracks => "heavyInfantryBarracks",
            BuildingGroup.HeroAcademy => "heroAcademy",
            BuildingGroup.HomeRunestone => "homeRunestone",
            BuildingGroup.IncenseMaker => "incenseMaker",
            BuildingGroup.InfantryBarracks => "infantryBarracks",
            BuildingGroup.IrrigationStation => "irrigationStation",
            BuildingGroup.JadeQuarry => "jadeQuarry",
            BuildingGroup.Jeweler => "jeweler",
            BuildingGroup.KaolinQuarry => "kaolinQuarry",
            BuildingGroup.LargeCulture => "largeCulture",
            BuildingGroup.LittleCulture => "littleCulture",
            BuildingGroup.MaskSculptor => "maskSculptor",
            BuildingGroup.MediumHome => "mediumHome",
            BuildingGroup.ModerateCulture => "moderateCulture",
            BuildingGroup.MothGlade => "mothGlade",
            BuildingGroup.NoriaIrrigation => "noriaIrrigation",
            BuildingGroup.Oasis => "oasis",
            BuildingGroup.OasisIrrigation => "oasisIrrigation",
            BuildingGroup.ObsidianQuarry => "obsidianQuarry",
            BuildingGroup.OilLampMaker => "oilLampMaker",
            BuildingGroup.PapyrusPress => "papyrusPress",
            BuildingGroup.PorcelainWorkshop => "porcelainWorkshop",
            BuildingGroup.PremiumAviary => "premiumAviary",
            BuildingGroup.PremiumCulture => "premiumCulture",
            BuildingGroup.PremiumFarm => "premiumFarm",
            BuildingGroup.PremiumGoldMine => "premiumGoldMine",
            BuildingGroup.PremiumHome => "premiumHome",
            BuildingGroup.PremiumIrrigation => "premiumIrrigation",
            BuildingGroup.PremiumMerchant => "premiumMerchant",
            BuildingGroup.PremiumPapyrusField => "premiumPapyrusField",
            BuildingGroup.PremiumPier => "premiumPier",
            BuildingGroup.PremiumQuarry => "premiumQuarry",
            BuildingGroup.PremiumRiceFarm => "premiumRiceFarm",
            BuildingGroup.PremiumRitualSite => "premiumRitualSite",
            BuildingGroup.PremiumSailorPort => "premiumSailorPort",
            BuildingGroup.PremiumWorkshop => "premiumWorkshop",
            BuildingGroup.PriestHome => "priestHome",
            BuildingGroup.RangedBarracks => "rangedBarracks",
            BuildingGroup.RitualCarver => "ritualCarver",
            BuildingGroup.RuralFarm => "ruralFarm",
            BuildingGroup.SailorHome => "sailorHome",
            BuildingGroup.SailorPort => "sailorPort",
            BuildingGroup.Scribe => "scribe",
            BuildingGroup.SiegeBarracks => "siegeBarracks",
            BuildingGroup.SilkWorkshop => "silkWorkshop",
            BuildingGroup.SmallHome => "smallHome",
            BuildingGroup.SmallIrrigation => "smallIrrigation",
            BuildingGroup.SmallRitualSite => "smallRitualSite",
            BuildingGroup.SmallWell => "smallWell",
            BuildingGroup.SpiceMerchant => "spiceMerchant",
            BuildingGroup.StoneMason => "stoneMason",
            BuildingGroup.Tailor => "tailor",
            BuildingGroup.Tavern => "tavern",
            BuildingGroup.TavernRunestone => "tavernRunestone",
            BuildingGroup.ThreadProcessor => "threadProcessor",
            BuildingGroup.WaterPump => "waterPump",
            BuildingGroup.WorkerHome => "workerHome",
            BuildingGroup.PresetFountain => "presetFountain",
            BuildingGroup.PresetOasis => "presetOasis",
            BuildingGroup.TutorialCityHall => "tutorialCityHall",
            BuildingGroup.PremiumPlantation => "premiumPlantation",
            BuildingGroup.AverageMasticGrove => "averageMasticGrove",
            BuildingGroup.AverageVineyard => "averageVineyard",
            BuildingGroup.OilPress => "oilPress",
            BuildingGroup.Vintner => "vintner",
            BuildingGroup.FisherHome => "fisherHome",
            BuildingGroup.DryingRacks => "dryingRacks",
            BuildingGroup.AverageOliveGrove => "averageOliveGrove",
            _ => string.Empty,
        };
    }
}
