version: '3.8'
services:
  nginx:
    container_name: localhost-cdn
    build: .
    image: localhost-cdn-nginx:latest
    ports:
      - "9080:80"
      - "9443:443"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./www:/usr/share/nginx/html/