//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ingweland.Fog.Application.Client.Web.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FogResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FogResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ingweland.Fog.Application.Client.Web.Localization.FogResource", typeof(FogResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Forge of Games: Your Ultimate Heroes of History Companion.
        /// </summary>
        public static string About_HeaderText {
            get {
                return ResourceManager.GetString("About.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access detailed campaign info for all regions, encounters and treasure hunt..
        /// </summary>
        public static string About_ListItem1 {
            get {
                return ResourceManager.GetString("About.ListItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dive into comprehensive hero stats and leveling resources..
        /// </summary>
        public static string About_ListItem2 {
            get {
                return ResourceManager.GetString("About.ListItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover unique historical insights about each hero, sourced directly from their real-life legends..
        /// </summary>
        public static string About_ListItem3 {
            get {
                return ResourceManager.GetString("About.ListItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use City Planner to optimize your city.
        /// </summary>
        public static string About_ListItem4 {
            get {
                return ResourceManager.GetString("About.ListItem4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether you&apos;re planning your campaigns, optimizing hero stats, or uncovering the history behind your favorite characters, Forge of Games is your ultimate companion..
        /// </summary>
        public static string About_Text1 {
            get {
                return ResourceManager.GetString("About.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More tools, including research calculators and city stats, are coming soon - stay tuned!.
        /// </summary>
        public static string About_Text2 {
            get {
                return ResourceManager.GetString("About.Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forge of Games.
        /// </summary>
        public static string BrandName {
            get {
                return ResourceManager.GetString("BrandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string CityPlanner_Area {
            get {
                return ResourceManager.GetString("CityPlanner.Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string CityPlanner_Cities {
            get {
                return ResourceManager.GetString("CityPlanner.Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City name.
        /// </summary>
        public static string CityPlanner_CityName {
            get {
                return ResourceManager.GetString("CityPlanner.CityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new city.
        /// </summary>
        public static string CityPlanner_CreateNewCity {
            get {
                return ResourceManager.GetString("CityPlanner.CreateNewCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customization.
        /// </summary>
        public static string CityPlanner_Customization {
            get {
                return ResourceManager.GetString("CityPlanner.Customization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture.
        /// </summary>
        public static string CityPlanner_Happiness {
            get {
                return ResourceManager.GetString("CityPlanner.Happiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excess.
        /// </summary>
        public static string CityPlanner_Happiness_Excess {
            get {
                return ResourceManager.GetString("CityPlanner.Happiness.Excess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total available.
        /// </summary>
        public static string CityPlanner_Happiness_TotalAvailable {
            get {
                return ResourceManager.GetString("CityPlanner.Happiness.TotalAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total consumed.
        /// </summary>
        public static string CityPlanner_Happiness_TotalConsumed {
            get {
                return ResourceManager.GetString("CityPlanner.Happiness.TotalConsumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmet need.
        /// </summary>
        public static string CityPlanner_Happiness_UnmetNeed {
            get {
                return ResourceManager.GetString("CityPlanner.Happiness.UnmetNeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage ratio.
        /// </summary>
        public static string CityPlanner_Happiness_UsageRatio {
            get {
                return ResourceManager.GetString("CityPlanner.Happiness.UsageRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string CityPlanner_Import {
            get {
                return ResourceManager.GetString("CityPlanner.Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional city planning tool for Heroes of History game. Import your in-game city, manage multiple layouts, analyze production and culture stats. Free web-based tool by Forge of Games..
        /// </summary>
        public static string CityPlanner_Meta_Description {
            get {
                return ResourceManager.GetString("CityPlanner.Meta.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heroes of History, HoH, city planner, city builder, game tools, Forge of Games, city layout, production calculator, city management, browser game tools, HoH calculator, city planning, city optimization.
        /// </summary>
        public static string CityPlanner_Meta_Keywords {
            get {
                return ResourceManager.GetString("CityPlanner.Meta.Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string CityPlanner_NameRequiredError {
            get {
                return ResourceManager.GetString("CityPlanner.NameRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot exceed {0} characters.
        /// </summary>
        public static string CityPlanner_NameTooLongError {
            get {
                return ResourceManager.GetString("CityPlanner.NameTooLongError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HoH City Planner | Heroes of History City Building Tool | Forge of Games.
        /// </summary>
        public static string CityPlanner_PageTitle {
            get {
                return ResourceManager.GetString("CityPlanner.PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        public static string CityPlanner_Production {
            get {
                return ResourceManager.GetString("CityPlanner.Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        public static string CityPlanner_Settings_Layout {
            get {
                return ResourceManager.GetString("CityPlanner.Settings.Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show levels.
        /// </summary>
        public static string CityPlanner_Settings_ShowLevels {
            get {
                return ResourceManager.GetString("CityPlanner.Settings.ShowLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show names.
        /// </summary>
        public static string CityPlanner_Settings_ShowNames {
            get {
                return ResourceManager.GetString("CityPlanner.Settings.ShowNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        public static string CityPlanner_Snapshots_Compare {
            get {
                return ResourceManager.GetString("CityPlanner.Snapshots.Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string CityPlanner_Snapshots_Current {
            get {
                return ResourceManager.GetString("CityPlanner.Snapshots.Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to load {0} snapshot? This will reset your current city. This action cannot be undone..
        /// </summary>
        public static string CityPlanner_Snapshots_LoadConfirmation {
            get {
                return ResourceManager.GetString("CityPlanner.Snapshots.LoadConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshots.
        /// </summary>
        public static string CityPlanner_Snapshots_Title {
            get {
                return ResourceManager.GetString("CityPlanner.Snapshots.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City planner.
        /// </summary>
        public static string CityPlanner_Title {
            get {
                return ResourceManager.GetString("CityPlanner.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workforce.
        /// </summary>
        public static string CityPlanner_Workforce {
            get {
                return ResourceManager.GetString("CityPlanner.Workforce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile name.
        /// </summary>
        public static string CommandCenter_CreateNewProfileDialog_InputLabel {
            get {
                return ResourceManager.GetString("CommandCenter.CreateNewProfileDialog.InputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new profile.
        /// </summary>
        public static string CommandCenter_CreateNewProfileDialog_Title {
            get {
                return ResourceManager.GetString("CommandCenter.CreateNewProfileDialog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team name.
        /// </summary>
        public static string CommandCenter_CreateNewTeamDialog_InputLabel {
            get {
                return ResourceManager.GetString("CommandCenter.CreateNewTeamDialog.InputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new team.
        /// </summary>
        public static string CommandCenter_CreateNewTeamDialog_Title {
            get {
                return ResourceManager.GetString("CommandCenter.CreateNewTeamDialog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create profile.
        /// </summary>
        public static string CommandCenter_CreateProfile {
            get {
                return ResourceManager.GetString("CommandCenter.CreateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete {0} team?.
        /// </summary>
        public static string CommandCenter_DeleteTeamDialog_Message {
            get {
                return ResourceManager.GetString("CommandCenter.DeleteTeamDialog.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string CommandCenter_Import {
            get {
                return ResourceManager.GetString("CommandCenter.Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heroes.
        /// </summary>
        public static string CommandCenter_Menu_Heroes {
            get {
                return ResourceManager.GetString("CommandCenter.Menu.Heroes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playgrounds.
        /// </summary>
        public static string CommandCenter_Menu_Playgrounds {
            get {
                return ResourceManager.GetString("CommandCenter.Menu.Playgrounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        public static string CommandCenter_Menu_Profiles {
            get {
                return ResourceManager.GetString("CommandCenter.Menu.Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan your Heroes of History teams, configure heroes, optimize battle strategies, and collaborate with alliance members. Features hero progression calculator, ability timers, profile sharing for Treasure Hunt planning, and more..
        /// </summary>
        public static string CommandCenter_Meta_Description {
            get {
                return ResourceManager.GetString("CommandCenter.Meta.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heroes of History, team planner, battle optimizer, treasure hunt, alliance collaboration, hero progression calculator, game strategy, profile sharing, command center, battle planner, HoH tool, HoH command center.
        /// </summary>
        public static string CommandCenter_Meta_Keywords {
            get {
                return ResourceManager.GetString("CommandCenter.Meta.Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Center - Heroes of History Team Planner &amp; Battle Optimizer | Forge of Games.
        /// </summary>
        public static string CommandCenter_PageTitle {
            get {
                return ResourceManager.GetString("CommandCenter.PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string CommandCenter_Profile_AddHeroDialog_OkButton {
            get {
                return ResourceManager.GetString("CommandCenter.Profile.AddHeroDialog.OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add hero.
        /// </summary>
        public static string CommandCenter_Profile_AddHeroDialog_Title {
            get {
                return ResourceManager.GetString("CommandCenter.Profile.AddHeroDialog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barracks.
        /// </summary>
        public static string CommandCenter_Profile_BarracksButton {
            get {
                return ResourceManager.GetString("CommandCenter.Profile.BarracksButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create team.
        /// </summary>
        public static string CommandCenter_Profile_CreateTeamButton {
            get {
                return ResourceManager.GetString("CommandCenter.Profile.CreateTeamButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add hero.
        /// </summary>
        public static string CommandCenter_Profile_Heroes_AddHeroButton {
            get {
                return ResourceManager.GetString("CommandCenter.Profile.Heroes.AddHeroButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heroes.
        /// </summary>
        public static string CommandCenter_Profile_HeroesButton {
            get {
                return ResourceManager.GetString("CommandCenter.Profile.HeroesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete profile.
        /// </summary>
        public static string CommandCenter_Profile_Settings_DeleteProfileButton {
            get {
                return ResourceManager.GetString("CommandCenter.Profile.Settings.DeleteProfileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile name.
        /// </summary>
        public static string CommandCenter_Profile_Settings_ProfileName {
            get {
                return ResourceManager.GetString("CommandCenter.Profile.Settings.ProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string CommandCenter_Profile_Team_EmptyTeamMessage {
            get {
                return ResourceManager.GetString("CommandCenter.Profile.Team.EmptyTeamMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove {0}?.
        /// </summary>
        public static string CommandCenter_RemoveHeroDialog_Message {
            get {
                return ResourceManager.GetString("CommandCenter.RemoveHeroDialog.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share city.
        /// </summary>
        public static string CommandCenter_ShareCityDialog_Title {
            get {
                return ResourceManager.GetString("CommandCenter.ShareCityDialog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share profile.
        /// </summary>
        public static string CommandCenter_ShareProfileDialog_Title {
            get {
                return ResourceManager.GetString("CommandCenter.ShareProfileDialog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Center.
        /// </summary>
        public static string CommandCenter_Title {
            get {
                return ResourceManager.GetString("CommandCenter.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1h.
        /// </summary>
        public static string Common_1h {
            get {
                return ResourceManager.GetString("Common.1h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24hrs.
        /// </summary>
        public static string Common_24hrs {
            get {
                return ResourceManager.GetString("Common.24hrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved..
        /// </summary>
        public static string Common_AllRightsReserved {
            get {
                return ResourceManager.GetString("Common.AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Common_Close {
            get {
                return ResourceManager.GetString("Common.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Common_Create {
            get {
                return ResourceManager.GetString("Common.Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Common_Delete {
            get {
                return ResourceManager.GetString("Common.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete {0}?.
        /// </summary>
        public static string Common_DeleteConfirmation {
            get {
                return ResourceManager.GetString("Common.DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer.
        /// </summary>
        public static string Common_Disclaimer {
            get {
                return ResourceManager.GetString("Common.Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forge of Games is a fan-made website dedicated to the game Heroes of History. All rights to the game, its assets, and intellectual property are owned by their respective holders. Users are encouraged to consult the official Innogames website for the most up-to-date and accurate information. Forge of Games is not affiliated with or officially connected to the creators or publishers of Heroes of History. The content here is created to support the game’s community by providing unique tools, guides, and insight [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Common_Disclaimer_Text {
            get {
                return ResourceManager.GetString("Common.Disclaimer.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        public static string Common_Hour_Abbr {
            get {
                return ResourceManager.GetString("Common.Hour.Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hrs.
        /// </summary>
        public static string Common_Hours_Abbr {
            get {
                return ResourceManager.GetString("Common.Hours.Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Common_Import {
            get {
                return ResourceManager.GetString("Common.Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Common_Info {
            get {
                return ResourceManager.GetString("Common.Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Discord.
        /// </summary>
        public static string Common_JoinDiscord {
            get {
                return ResourceManager.GetString("Common.JoinDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Common_Load {
            get {
                return ResourceManager.GetString("Common.Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Common_Next {
            get {
                return ResourceManager.GetString("Common.Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Common_Ok {
            get {
                return ResourceManager.GetString("Common.Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Common_Previous {
            get {
                return ResourceManager.GetString("Common.Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more....
        /// </summary>
        public static string Common_ReadMore {
            get {
                return ResourceManager.GetString("Common.ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Common_Remove {
            get {
                return ResourceManager.GetString("Common.Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Common_Search {
            get {
                return ResourceManager.GetString("Common.Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Common_Settings {
            get {
                return ResourceManager.GetString("Common.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Common_Share {
            get {
                return ResourceManager.GetString("Common.Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a hero. Start typing the name or select from the list..
        /// </summary>
        public static string HeroSelector_HelperText {
            get {
                return ResourceManager.GetString("HeroSelector.HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle.
        /// </summary>
        public static string Hoh_Battle {
            get {
                return ResourceManager.GetString("Hoh.Battle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building.
        /// </summary>
        public static string Hoh_Building {
            get {
                return ResourceManager.GetString("Hoh.Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction cost.
        /// </summary>
        public static string Hoh_Building_ConstructionCost {
            get {
                return ResourceManager.GetString("Hoh.Building.ConstructionCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade cost.
        /// </summary>
        public static string Hoh_Building_UpgradeCost {
            get {
                return ResourceManager.GetString("Hoh.Building.UpgradeCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign.
        /// </summary>
        public static string Hoh_Campaign {
            get {
                return ResourceManager.GetString("Hoh.Campaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Hoh_City {
            get {
                return ResourceManager.GetString("Hoh.City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string Hoh_Cost {
            get {
                return ResourceManager.GetString("Hoh.Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encounters.
        /// </summary>
        public static string Hoh_Encounters {
            get {
                return ResourceManager.GetString("Hoh.Encounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hero.
        /// </summary>
        public static string Hoh_Hero {
            get {
                return ResourceManager.GetString("Hoh.Hero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ability.
        /// </summary>
        public static string Hoh_Hero_Ability {
            get {
                return ResourceManager.GetString("Hoh.Hero.Ability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ability lvl..
        /// </summary>
        public static string Hoh_Hero_AbilityLvl {
            get {
                return ResourceManager.GetString("Hoh.Hero.AbilityLvl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awakening.
        /// </summary>
        public static string Hoh_Hero_Awakening {
            get {
                return ResourceManager.GetString("Hoh.Hero.Awakening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barracks.
        /// </summary>
        public static string Hoh_Hero_Barracks {
            get {
                return ResourceManager.GetString("Hoh.Hero.Barracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Hoh_Hero_Create {
            get {
                return ResourceManager.GetString("Hoh.Hero.Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string Hoh_Hero_Main {
            get {
                return ResourceManager.GetString("Hoh.Hero.Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heroes.
        /// </summary>
        public static string Hoh_Heroes {
            get {
                return ResourceManager.GetString("Hoh.Heroes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels.
        /// </summary>
        public static string Hoh_Levels {
            get {
                return ResourceManager.GetString("Hoh.Levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lvl..
        /// </summary>
        public static string Hoh_Lvl {
            get {
                return ResourceManager.GetString("Hoh.Lvl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research.
        /// </summary>
        public static string Hoh_Research {
            get {
                return ResourceManager.GetString("Hoh.Research", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource.
        /// </summary>
        public static string Hoh_Resource {
            get {
                return ResourceManager.GetString("Hoh.Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cummulative cost.
        /// </summary>
        public static string Hoh_Wonder_CummulativeCost {
            get {
                return ResourceManager.GetString("Hoh.Wonder.CummulativeCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World wonder.
        /// </summary>
        public static string Hoh_WorldWonder {
            get {
                return ResourceManager.GetString("Hoh.WorldWonder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forge of Games: The ultimate Heroes of History wiki, resource and tool hub. Discover campaign details, hero information, and more..
        /// </summary>
        public static string Home_Meta_Description {
            get {
                return ResourceManager.GetString("Home.Meta.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heroes of History, wiki, strategy game, game guide, game tools, Innogames.
        /// </summary>
        public static string Home_Meta_Keywords {
            get {
                return ResourceManager.GetString("Home.Meta.Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import your in-game data.
        /// </summary>
        public static string ImportInGameData_Headline {
            get {
                return ResourceManager.GetString("ImportInGameData.Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data with id {0} could not be found..
        /// </summary>
        public static string ImportInGameData_NotFound {
            get {
                return ResourceManager.GetString("ImportInGameData.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capital city.
        /// </summary>
        public static string ImportInGameData_Options_Cities {
            get {
                return ResourceManager.GetString("ImportInGameData.Options.Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command center profile.
        /// </summary>
        public static string ImportInGameData_Options_Profile {
            get {
                return ResourceManager.GetString("ImportInGameData.Options.Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has been imported successfully. Open City planner or Command center to see it..
        /// </summary>
        public static string ImportInGameData_SuccessMessage {
            get {
                return ResourceManager.GetString("ImportInGameData.SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Navigation_About {
            get {
                return ResourceManager.GetString("Navigation.About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buildings.
        /// </summary>
        public static string Navigation_Buildings {
            get {
                return ResourceManager.GetString("Navigation.Buildings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign.
        /// </summary>
        public static string Navigation_Campaign {
            get {
                return ResourceManager.GetString("Navigation.Campaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Navigation_Home {
            get {
                return ResourceManager.GetString("Navigation.Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string Navigation_More {
            get {
                return ResourceManager.GetString("Navigation.More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Us.
        /// </summary>
        public static string Navigation_SupportUs {
            get {
                return ResourceManager.GetString("Navigation.SupportUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Navigation_Tools {
            get {
                return ResourceManager.GetString("Navigation.Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treasure Hunt.
        /// </summary>
        public static string Navigation_TreasureHunt {
            get {
                return ResourceManager.GetString("Navigation.TreasureHunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wonders.
        /// </summary>
        public static string Navigation_Wonders {
            get {
                return ResourceManager.GetString("Navigation.Wonders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create link.
        /// </summary>
        public static string ShareDialog_ShareButton {
            get {
                return ResourceManager.GetString("ShareDialog.ShareButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan your Heroes of History teams, configure heroes, optimize battle strategies, and collaborate with alliance members. Features hero progression calculator, ability timers, profile sharing for Treasure Hunt planning, and more..
        /// </summary>
        public static string StatsHub_Meta_Description {
            get {
                return ResourceManager.GetString("StatsHub.Meta.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heroes of History, team planner, battle optimizer, treasure hunt, alliance collaboration, hero progression calculator, game strategy, profile sharing, command center, battle planner, HoH tool, HoH command center.
        /// </summary>
        public static string StatsHub_Meta_Keywords {
            get {
                return ResourceManager.GetString("StatsHub.Meta.Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats Hub - Heroes of History Stats &amp; Leaderboards | Forge of Games.
        /// </summary>
        public static string StatsHub_PageTitle {
            get {
                return ResourceManager.GetString("StatsHub.PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string StatsHub_Player_Age {
            get {
                return ResourceManager.GetString("StatsHub.Player.Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ages.
        /// </summary>
        public static string StatsHub_Player_Ages {
            get {
                return ResourceManager.GetString("StatsHub.Player.Ages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alliance.
        /// </summary>
        public static string StatsHub_Player_Alliance {
            get {
                return ResourceManager.GetString("StatsHub.Player.Alliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alliances.
        /// </summary>
        public static string StatsHub_Player_Alliances {
            get {
                return ResourceManager.GetString("StatsHub.Player.Alliances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string StatsHub_Player_Name {
            get {
                return ResourceManager.GetString("StatsHub.Player.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names.
        /// </summary>
        public static string StatsHub_Player_Names {
            get {
                return ResourceManager.GetString("StatsHub.Player.Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        public static string StatsHub_Player_Rank {
            get {
                return ResourceManager.GetString("StatsHub.Player.Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking Points.
        /// </summary>
        public static string StatsHub_Player_RankingPoints {
            get {
                return ResourceManager.GetString("StatsHub.Player.RankingPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated on.
        /// </summary>
        public static string StatsHub_Player_UpdatedOn {
            get {
                return ResourceManager.GetString("StatsHub.Player.UpdatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World.
        /// </summary>
        public static string StatsHub_Player_World {
            get {
                return ResourceManager.GetString("StatsHub.Player.World", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats Hub.
        /// </summary>
        public static string StatsHub_Title {
            get {
                return ResourceManager.GetString("StatsHub.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated on {0}.
        /// </summary>
        public static string StatsHub_UpdatedOn {
            get {
                return ResourceManager.GetString("StatsHub.UpdatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All.
        /// </summary>
        public static string StatsHub_ViewAll {
            get {
                return ResourceManager.GetString("StatsHub.ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta world.
        /// </summary>
        public static string StatsHub_Worlds_BetaWorld {
            get {
                return ResourceManager.GetString("StatsHub.Worlds.BetaWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main world.
        /// </summary>
        public static string StatsHub_Worlds_MainWorld {
            get {
                return ResourceManager.GetString("StatsHub.Worlds.MainWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players on {0}.
        /// </summary>
        public static string StatsHub_Worlds_PlayerListTitle {
            get {
                return ResourceManager.GetString("StatsHub.Worlds.PlayerListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top players on {0}.
        /// </summary>
        public static string StatsHub_Worlds_TopPlayerListTitle {
            get {
                return ResourceManager.GetString("StatsHub.Worlds.TopPlayerListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you find our tools helpful, consider supporting the project with a small donation..
        /// </summary>
        public static string SupportUs_Message {
            get {
                return ResourceManager.GetString("SupportUs.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Forge of Games.
        /// </summary>
        public static string SupportUs_PageTitle {
            get {
                return ResourceManager.GetString("SupportUs.PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep our tools free and accessible for everyone in the gaming community.
        /// </summary>
        public static string SupportUs_Why_Reason1 {
            get {
                return ResourceManager.GetString("SupportUs.Why.Reason1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support ongoing development of new features and improvements.
        /// </summary>
        public static string SupportUs_Why_Reason2 {
            get {
                return ResourceManager.GetString("SupportUs.Why.Reason2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help cover server and maintenance costs.
        /// </summary>
        public static string SupportUs_Why_Reason3 {
            get {
                return ResourceManager.GetString("SupportUs.Why.Reason3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be part of our growing gaming community.
        /// </summary>
        public static string SupportUs_Why_Reason4 {
            get {
                return ResourceManager.GetString("SupportUs.Why.Reason4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why Support Us?.
        /// </summary>
        public static string SupportUs_Why_Title {
            get {
                return ResourceManager.GetString("SupportUs.Why.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate the resources needed to build or upgrade a building..
        /// </summary>
        public static string Tools_BuildingCost_Description {
            get {
                return ResourceManager.GetString("Tools.BuildingCost.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building cost calculator.
        /// </summary>
        public static string Tools_BuildingCost_Name {
            get {
                return ResourceManager.GetString("Tools.BuildingCost.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current level.
        /// </summary>
        public static string Tools_CurrentLevel {
            get {
                return ResourceManager.GetString("Tools.CurrentLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure your hero&apos;s potential by adjusting all four critical properties..
        /// </summary>
        public static string Tools_HeroBuilder_Description {
            get {
                return ResourceManager.GetString("Tools.HeroBuilder.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hero builder.
        /// </summary>
        public static string Tools_HeroBuilder_Name {
            get {
                return ResourceManager.GetString("Tools.HeroBuilder.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate the resources needed to level up a hero..
        /// </summary>
        public static string Tools_HeroProgressionResourcesCalculator_Description {
            get {
                return ResourceManager.GetString("Tools.HeroProgressionResourcesCalculator.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hero progression calculator.
        /// </summary>
        public static string Tools_HeroProgressionResourcesCalculator_Name {
            get {
                return ResourceManager.GetString("Tools.HeroProgressionResourcesCalculator.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate the resources required to open technologies..
        /// </summary>
        public static string Tools_ResearchCalculator_Description {
            get {
                return ResourceManager.GetString("Tools.ResearchCalculator.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research calculator.
        /// </summary>
        public static string Tools_ResearchCalculator_Name {
            get {
                return ResourceManager.GetString("Tools.ResearchCalculator.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost of the technologies..
        /// </summary>
        public static string Tools_ResearchCalculator_Result {
            get {
                return ResourceManager.GetString("Tools.ResearchCalculator.Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick the last technologies you have discovered..
        /// </summary>
        public static string Tools_ResearchCalculator_SelectOpenTech {
            get {
                return ResourceManager.GetString("Tools.ResearchCalculator.SelectOpenTech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick technologies you want to discover..
        /// </summary>
        public static string Tools_ResearchCalculator_SelectTargetTech {
            get {
                return ResourceManager.GetString("Tools.ResearchCalculator.SelectTargetTech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target level.
        /// </summary>
        public static string Tools_TargetLevel {
            get {
                return ResourceManager.GetString("Tools.TargetLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate the resources required to progress through world wonder levels..
        /// </summary>
        public static string Tools_WonderCost_Description {
            get {
                return ResourceManager.GetString("Tools.WonderCost.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World wonder calculator.
        /// </summary>
        public static string Tools_WonderCost_Name {
            get {
                return ResourceManager.GetString("Tools.WonderCost.Name", resourceCulture);
            }
        }
    }
}
