using ProtoBuf;

namespace Ingweland.Fog.Models.Hoh.Enums;

[ProtoContract]
public enum UnitStatType
{
    Undefined = 0,
    Accuracy,
    AoeDamageAmp,
    AoeDamageTakenAmp,
    AssetRadius,
    Attack,
    AttackRadius,
    AttackRange,
    AttackSpeed,
    BaseDamage,
    BasicAttackDamageAmp,
    BasicAttackDamageTakenAmp,
    BleedDamageAmp,
    BleedDamageTakenAmp,
    BurnDamageAmp,
    BurnDamageTakenAmp,
    CritChance,
    CritDamage,
    Defense,
    DotDamageAmp,
    DotDamageTakenAmp,
    Evasion,
    ExpectedSquadSize,
    Focus,
    FocusRegen,
    HealGivenAmp,
    HealTakenAmp,
    HitPoints,
    HitTime,
    InitialFocusInSecondsBonus,
    MaxFocus,
    MaxHitPoints,
    MoveSpeed,
    PoisonDamageAmp,
    PoisonDamageTakenAmp,
    ProjectileSpeed,
    Shield,
    ShieldTakenAmp,
    SingleTargetDamageAmp,
    SingleTargetDamageTakenAmp,
    SplashDamageDivisor,
    SquadRows,
    SquadSize,
    SquadSpacingX,
    SquadSpacingY,
    StatusEffectDurationAmp,
    StunDurationAmp,
    StunDurationTakenAmp,
}