namespace Ingweland.Fog.Models.Hoh.Enums;

public enum WonderId
{
    Undefined = 0,
    Capital_Alhambra,
    Capital_Carcassonne,
    Capital_Colosseum,
    Capital_Colossus,
    Capital_HagiaSophia,
    Capital_HangingGardens,
    Capital_Lighthouse,
    Capital_Mausoleum,
    Capital_PalaceOfAachen,
    Capital_SherwoodForest,
    Capital_StatueOfZeus,
    Capital_Stonehenge,
    Capital_TempleOfArtemis,
    Capital_TowerOfPisa,
    China_ForbiddenCity,
    China_GreatWall,
    China_TerracottaArmy,
    Egypt_AbuSimbel,
    Egypt_CheopsPyramid,
    Egypt_GreatSphinx,
    Mayas_ChichenItza,
    Mayas_SayilPalace,
    Mayas_Tikal,
    Vikings_DragonshipEllida,
    Vikings_Valhalla,
    Vikings_Yggdrasil,
    Arabia_CityOfBrass,
    Arabia_NoriasOfHama,
    Arabia_Petra,
    AncientEgyptEvent_AnubisTemple,
    Ithaka_PenelopesHearth,
}
