using Ingweland.Fog.Models.Hoh.Enums;

namespace HohProtoParser.Extensions;

public static class BuildingSubtypeExtensions
{
    public static BuildingGroup ToBuildingSubtype(this string value)
    {
        return value switch
        {
            "alchemist" => BuildingGroup.Alchemist,
            "artisan" => BuildingGroup.Artisan,
            "averageAviary" => BuildingGroup.AverageAviary,
            "averageBeehive" => BuildingGroup.AverageBeehive,
            "averageCamelFarm" => BuildingGroup.AverageCamelFarm,
            "averageGoldMine" => BuildingGroup.AverageGoldMine,
            "averageHome" => BuildingGroup.AverageHome,
            "averageMerchant" => BuildingGroup.AverageMerchant,
            "averagePapyrusField" => BuildingGroup.AveragePapyrusField,
            "averagePier" => BuildingGroup.AveragePier,
            "averageRiceFarm" => BuildingGroup.AverageRiceFarm,
            "averageRitualSite" => BuildingGroup.AverageRitualSite,
            "beehiveRunestone" => BuildingGroup.BeehiveRunestone,
            "carpenter" => BuildingGroup.Carpenter,
            "cavalryBarracks" => BuildingGroup.CavalryBarracks,
            "ceremonyOutfitter" => BuildingGroup.CeremonyOutfitter,
            "channel" => BuildingGroup.Channel,
            "chronicler" => BuildingGroup.Chronicler,
            "cityHall" => BuildingGroup.CityHall,
            "clayProcessor" => BuildingGroup.ClayProcessor,
            "coffeeBrewer" => BuildingGroup.CoffeeBrewer,
            "collectableAmphitheatre" => BuildingGroup.CollectableAmphitheatre,
            "collectableArchitectsStudioV2" => BuildingGroup.CollectableArchitectsStudioV2,
            "collectableMinoanWatchtowerV2" => BuildingGroup.CollectableMinoanWatchtowerV2,
            "collectableSchoolV2" => BuildingGroup.CollectableSchoolV2,
            "compactCulture" => BuildingGroup.CompactCulture,
            "domesticFarm" => BuildingGroup.DomesticFarm,
            "evolvingFountainOfYouth" => BuildingGroup.EvolvingFountainOfYouth,
            "evolvingGarden" => BuildingGroup.EvolvingGarden,
            "expeditionPier" => BuildingGroup.ExpeditionPier,
            "expeditionPort" => BuildingGroup.ExpeditionPort,
            "fountain" => BuildingGroup.Fountain,
            "furnace" => BuildingGroup.Furnace,
            "goldsmith" => BuildingGroup.Goldsmith,
            "glassblower" => BuildingGroup.Glassblower,
            "heavyInfantryBarracks" => BuildingGroup.HeavyInfantryBarracks,
            "heroAcademy" => BuildingGroup.HeroAcademy,
            "homeRunestone" => BuildingGroup.HomeRunestone,
            "incenseMaker" => BuildingGroup.IncenseMaker,
            "infantryBarracks" => BuildingGroup.InfantryBarracks,
            "irrigationStation" => BuildingGroup.IrrigationStation,
            "jadeQuarry" => BuildingGroup.JadeQuarry,
            "jeweler" => BuildingGroup.Jeweler,
            "kaolinQuarry" => BuildingGroup.KaolinQuarry,
            "largeCulture" => BuildingGroup.LargeCulture,
            "littleCulture" => BuildingGroup.LittleCulture,
            "maskSculptor" => BuildingGroup.MaskSculptor,
            "moderateCulture" => BuildingGroup.ModerateCulture,
            "mothGlade" => BuildingGroup.MothGlade,
            "oasis" => BuildingGroup.Oasis,
            "oasisIrrigation" => BuildingGroup.OasisIrrigation,
            "obsidianQuarry" => BuildingGroup.ObsidianQuarry,
            "papyrusPress" => BuildingGroup.PapyrusPress,
            "porcelainWorkshop" => BuildingGroup.PorcelainWorkshop,
            "premiumAviary" => BuildingGroup.PremiumAviary,
            "premiumCulture" => BuildingGroup.PremiumCulture,
            "premiumFarm" => BuildingGroup.PremiumFarm,
            "premiumGoldMine" => BuildingGroup.PremiumGoldMine,
            "premiumHome" => BuildingGroup.PremiumHome,
            "premiumMerchant" => BuildingGroup.PremiumMerchant,
            "premiumPapyrusField" => BuildingGroup.PremiumPapyrusField,
            "premiumPier" => BuildingGroup.PremiumPier,
            "premiumQuarry" => BuildingGroup.PremiumQuarry,
            "premiumRiceFarm" => BuildingGroup.PremiumRiceFarm,
            "premiumRitualSite" => BuildingGroup.PremiumRitualSite,
            "premiumSailorPort" => BuildingGroup.PremiumSailorPort,
            "premiumWorkshop" => BuildingGroup.PremiumWorkshop,
            "priestHome" => BuildingGroup.PriestHome,
            "rangedBarracks" => BuildingGroup.RangedBarracks,
            "ritualCarver" => BuildingGroup.RitualCarver,
            "ruralFarm" => BuildingGroup.RuralFarm,
            "sailorHome" => BuildingGroup.SailorHome,
            "sailorPort" => BuildingGroup.SailorPort,
            "scribe" => BuildingGroup.Scribe,
            "siegeBarracks" => BuildingGroup.SiegeBarracks,
            "silkWorkshop" => BuildingGroup.SilkWorkshop,
            "smallHome" => BuildingGroup.SmallHome,
            "smallIrrigation" => BuildingGroup.SmallIrrigation,
            "smallRitualSite" => BuildingGroup.SmallRitualSite,
            "smallWell" => BuildingGroup.SmallWell,
            "spiceMerchant" => BuildingGroup.SpiceMerchant,
            "stoneMason" => BuildingGroup.StoneMason,
            "tailor" => BuildingGroup.Tailor,
            "tavern" => BuildingGroup.Tavern,
            "tavernRunestone" => BuildingGroup.TavernRunestone,
            "threadProcessor" => BuildingGroup.ThreadProcessor,
            "waterPump" => BuildingGroup.WaterPump,
            "workerHome" => BuildingGroup.WorkerHome,
            _ => throw new Exception($"Cannot map building subtype: {value}"),
        };
    }
}
