// <auto-generated />
using System;
using Ingweland.Fog.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ingweland.Fog.Infrastructure.Migrations
{
    [DbContext(typeof(FogDbContext))]
    [Migration("20260712100145_WoaPlayerStats")]
    partial class WoaPlayerStats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlliancePlayer", b =>
                {
                    b.Property<int>("AllianceHistoryId")
                        .HasColumnType("int");

                    b.Property<int>("MemberHistoryId")
                        .HasColumnType("int");

                    b.HasKey("AllianceHistoryId", "MemberHistoryId");

                    b.HasIndex("MemberHistoryId");

                    b.ToTable("AlliancePlayer");
                });

            modelBuilder.Entity("BattleSummaryEntityBattleUnitEntity", b =>
                {
                    b.Property<int>("BattlesId")
                        .HasColumnType("int");

                    b.Property<int>("UnitsId")
                        .HasColumnType("int");

                    b.HasKey("BattlesId", "UnitsId");

                    b.HasIndex("UnitsId");

                    b.ToTable("battles_to_units", (string)null);
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.Alliance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BannerCrestColorId")
                        .HasColumnType("int");

                    b.Property<int>("BannerCrestId")
                        .HasColumnType("int");

                    b.Property<int>("BannerIconColorId")
                        .HasColumnType("int");

                    b.Property<int>("BannerIconId")
                        .HasColumnType("int");

                    b.Property<int>("InGameAllianceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MembersUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("RankingPoints")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateOnly>("UpdatedAt")
                        .HasColumnType("date");

                    b.Property<string>("WorldId")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.HasKey("Id");

                    b.HasIndex("InGameAllianceId");

                    b.HasIndex("MembersUpdatedAt")
                        .IsDescending();

                    b.HasIndex("Name");

                    b.HasIndex("RankingPoints")
                        .IsDescending();

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedAt")
                        .IsDescending();

                    b.HasIndex("WorldId");

                    b.HasIndex("WorldId", "InGameAllianceId")
                        .IsUnique();

                    b.ToTable("alliances", (string)null);
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.AllianceAthRanking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AllianceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InGameEventId")
                        .HasColumnType("int");

                    b.Property<int>("League")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InGameEventId");

                    b.HasIndex("League");

                    b.HasIndex("Points")
                        .IsDescending();

                    b.HasIndex("AllianceId", "InGameEventId")
                        .IsUnique();

                    b.ToTable("alliance_ath_rankings", (string)null);
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.AllianceMemberEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AllianceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("AllianceId");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.HasIndex("Role");

                    b.ToTable("alliance_members", (string)null);
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.AllianceNameHistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AllianceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("AllianceId", "Name", "ChangedAt")
                        .IsUnique();

                    b.ToTable("alliance_name_history_entries", (string)null);
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.AllianceRanking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AllianceId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("CollectedAt")
                        .HasColumnType("date");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CollectedAt")
                        .IsDescending();

                    b.HasIndex("Type", "CollectedAt");

                    b.HasIndex("AllianceId", "Type", "CollectedAt");

                    b.ToTable("alliance_rankings", (string)null);
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.AllianceWoaRanking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AllianceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.Property<int>("EloDelta")
                        .HasColumnType("int");

                    b.Property<int>("EloRating")
                        .HasColumnType("int");

                    b.Property<double>("ExpectedVictoryPointsShare")
                        .HasColumnType("float");

                    b.Property<int>("InGameEventId")
                        .HasColumnType("int");

                    b.Property<int>("VictoryPoints")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.HasIndex("EloRating")
                        .IsDescending();

                    b.HasIndex("InGameEventId");

                    b.HasIndex("AllianceId", "InGameEventId", "DivisionId")
                        .IsUnique();

                    b.ToTable("alliance_woa_rankings", (string)null);
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.AnnualBudget", b =>
                {
                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<float>("ServerContributions")
                        .HasColumnType("real");

                    b.Property<int>("ServerGoal")
                        .HasColumnType("int");

                    b.HasKey("Year");

                    b.ToTable("annual_budgets", (string)null);
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.BattleSquadStatsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BattleStatsId")
                        .HasColumnType("int");

                    b.Property<int?>("HeroId")
                        .HasColumnType("int");

                    b.Property<int>("Side")
                        .HasColumnType("int");

                    b.Property<int?>("SupportUnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BattleStatsId");

                    b.HasIndex("HeroId");

                    b.HasIndex("SupportUnitId");

                    b.ToTable("battle_squad_stats", (string)null);
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.BattleSquadsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BattleId")
                        .HasColumnType("int");

                    b.Property<int>("Side")
                        .HasColumnType("int");

                    b.Property<byte[]>("Squads")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("BattleId");

                    b.HasIndex("Side");

                    b.ToTable("battle_squads", (string)null);
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.BattleStatsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("InGameBattleId")
                        .IsRequired()
                        .HasColumnType("varbinary(900)");

                    b.HasKey("Id");

                    b.HasIndex("InGameBattleId")
                        .IsUnique();

                    b.ToTable("battle_stats", (string)null);
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.BattleSummaryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BattleDefinitionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte>("BattleType")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Difficulty")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("InGameBattleId")
                        .IsRequired()
                        .HasColumnType("varbinary(900)");

                    b.Property<DateOnly>("PerformedAt")
                        .HasColumnType("date");

                    b.Property<byte>("ResultStatus")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WorldId")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.HasKey("Id");

                    b.HasIndex("BattleType");

                    b.HasIndex("InGameBattleId")
                        .IsUnique();

                    b.HasIndex("ResultStatus");

                    b.HasIndex("BattleDefinitionId", "Id")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_battles_BattleDefinitionId_Id_Desc");

                    b.HasIndex("BattleDefinitionId", "ResultStatus", "Id")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_battles_BattleDefinitionId_ResultStatus_Id_Desc");

                    b.HasIndex("SubmissionId", "BattleType", "BattleDefinitionId", "ResultStatus", "Id")
                        .IsDescending(false, false, false, false, true)
                        .HasDatabaseName("IX_battles_SubmissionId_BattleType_BattleDefinitionId_ResultStatus_Id_Desc");

                    b.ToTable("battles", (string)null);
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.BattleTimelineEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Entries")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("InGameBattleId")
                        .IsRequired()
                        .HasColumnType("varbinary(900)");

                    b.HasKey("Id");

                    b.HasIndex("InGameBattleId");

                    b.ToTable("battle_timelines", (string)null);
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.BattleUnitEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("Side")
                        .HasColumnType("int");

                    b.Property<string>("UnitId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Level");

                    b.HasIndex("Side");

                    b.HasIndex("UnitId");

                    b.HasIndex("UnitId", "Level", "Side")
                        .IsUnique();

                    b.ToTable("battle_units", (string)null);
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.CommunityCityGuideEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WonderId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("community_city_guides", (string)null);
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.CommunityCityStrategyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("SharedDataId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WonderId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("community_city_strategies", (string)null);
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.EquipmentInsightsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EquipmentSets")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EquipmentSlotType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FromLevel")
                        .HasColumnType("int");

                    b.Property<string>("MainAttributes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubAttributesLevel12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubAttributesLevel16")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubAttributesLevel4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubAttributesLevel8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToLevel")
                        .HasColumnType("int");

                    b.Property<string>("UnitId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentSlotType");

                    b.HasIndex("FromLevel");

                    b.HasIndex("ToLevel");

                    b.HasIndex("UnitId");

                    b.HasIndex("UnitId", "EquipmentSlotType", "FromLevel", "ToLevel")
                        .IsUnique();

                    b.ToTable("equipment_insights", (string)null);
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.EventCityFetchState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("FailuresCount")
                        .HasColumnType("int");

                    b.Property<string>("FetchTimestamps")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameWorldId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InGamePlayerId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("EventId", "PlayerId")
                        .IsUnique();

                    b.ToTable("event_city_fetch_states", (string)null);
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.EventCitySnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasPremiumBuildings")
                        .HasColumnType("bit");

                    b.Property<int>("InGameEventId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("PremiumExpansionCount")
                        .HasColumnType("int");

                    b.Property<string>("WonderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("HasPremiumBuildings");

                    b.HasIndex("InGameEventId");

                    b.HasIndex("PlayerId", "CityId", "WonderId");

                    b.ToTable("event_city_snapshots", (string)null);
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.EventCitySnapshotDataEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("EventCitySnapshotId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventCitySnapshotId")
                        .IsUnique();

                    b.ToTable("event_city_snapshot_data", (string)null);
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.EventCityStrategy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("HasPremiumBuildings")
                        .HasColumnType("bit");

                    b.Property<bool>("HasPremiumExpansion")
                        .HasColumnType("bit");

                    b.Property<int>("InGameEventId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("WonderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("HasPremiumBuildings");

                    b.HasIndex("HasPremiumExpansion");

                    b.HasIndex("InGameEventId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("CityId", "WonderId");

                    b.ToTable("event_city_strategy", (string)null);
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.EventCityStrategyDataEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("EventCityStrategyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventCityStrategyId")
                        .IsUnique();

                    b.ToTable("event_city_strategy_data", (string)null);
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.EventCityWonderRanking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InGameEventId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("WonderLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InGameEventId");

                    b.HasIndex("PlayerId", "InGameEventId")
                        .IsUnique();

                    b.ToTable("event_city_wonder_rankings", (string)null);
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.HeroAbilityFeaturesEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Locale", "HeroId")
                        .IsUnique();

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Locale", "HeroId"), new[] { "Tags", "Attributes" });

                    b.ToTable("hero_ability_features", (string)null);
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.InGameEventEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DefinitionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("InGameDefinitionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorldId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DefinitionId");

                    b.HasIndex("EventId");

                    b.HasIndex("WorldId");

                    b.HasIndex("WorldId", "DefinitionId", "EventId")
                        .IsUnique();

                    b.ToTable("in_game_events", (string)null);
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("AvatarId")
                        .HasColumnType("int");

                    b.Property<int>("InGamePlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastSeenOnline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("ProfileUpdatedAt")
                        .HasColumnType("date");

                    b.Property<int?>("Rank")
                        .HasColumnType("int");

                    b.Property<int?>("RankingPoints")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TreasureHuntDifficulty")
                        .HasColumnType("int");

                    b.Property<DateOnly>("UpdatedAt")
                        .HasColumnType("date");

                    b.Property<string>("WorldId")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.HasKey("Id");

                    b.HasIndex("InGamePlayerId");

                    b.HasIndex("LastSeenOnline")
                        .IsDescending();

                    b.HasIndex("Name");

                    b.HasIndex("ProfileUpdatedAt")
                        .IsDescending();

                    b.HasIndex("RankingPoints")
                        .IsDescending();

                    b.HasIndex("Status");

                    b.HasIndex("WorldId", "InGamePlayerId")
                        .IsUnique();

                    b.HasIndex("WorldId", "Status", "RankingPoints", "Rank")
                        .IsDescending(false, false, true, false)
                        .HasDatabaseName("IX_players_WorldId_Status_RankingPoints_Rank");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("WorldId", "Status", "RankingPoints", "Rank"), new[] { "Id", "Age", "AvatarId", "Name", "UpdatedAt" });

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.PlayerAgeHistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "Age", "ChangedAt")
                        .IsUnique();

                    b.ToTable("player_age_history_entries", (string)null);
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.PlayerAthRanking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InGameEventId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InGameEventId");

                    b.HasIndex("Points")
                        .IsDescending();

                    b.HasIndex("PlayerId", "InGameEventId")
                        .IsUnique();

                    b.ToTable("player_ath_rankings", (string)null);
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.PlayerCitySnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Coins")
                        .HasColumnType("int");

                    b.Property<int>("Coins1H")
                        .HasColumnType("int");

                    b.Property<int>("Coins1HPerArea")
                        .HasColumnType("int");

                    b.Property<int>("Coins24H")
                        .HasColumnType("int");

                    b.Property<int>("Coins24HPerArea")
                        .HasColumnType("int");

                    b.Property<int>("CoinsPerArea")
                        .HasColumnType("int");

                    b.Property<DateOnly>("CollectedAt")
                        .HasColumnType("date");

                    b.Property<int>("Food")
                        .HasColumnType("int");

                    b.Property<int>("Food1H")
                        .HasColumnType("int");

                    b.Property<int>("Food1HPerArea")
                        .HasColumnType("int");

                    b.Property<int>("Food24H")
                        .HasColumnType("int");

                    b.Property<int>("Food24HPerArea")
                        .HasColumnType("int");

                    b.Property<int>("FoodPerArea")
                        .HasColumnType("int");

                    b.Property<int>("Goods")
                        .HasColumnType("int");

                    b.Property<int>("Goods1H")
                        .HasColumnType("int");

                    b.Property<int>("Goods1HPerArea")
                        .HasColumnType("int");

                    b.Property<int>("Goods24H")
                        .HasColumnType("int");

                    b.Property<int>("Goods24HPerArea")
                        .HasColumnType("int");

                    b.Property<int>("GoodsPerArea")
                        .HasColumnType("int");

                    b.Property<float>("HappinessUsageRatio")
                        .HasColumnType("real");

                    b.Property<bool>("HasPremiumCultureBuildings")
                        .HasColumnType("bit");

                    b.Property<bool>("HasPremiumFarmBuildings")
                        .HasColumnType("bit");

                    b.Property<bool>("HasPremiumHomeBuildings")
                        .HasColumnType("bit");

                    b.Property<string>("OpenedExpansionsHash")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("char(16)")
                        .IsFixedLength();

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("PremiumExpansionCount")
                        .HasColumnType("int");

                    b.Property<int>("TotalArea")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Coins")
                        .IsDescending();

                    b.HasIndex("Coins1H")
                        .IsDescending();

                    b.HasIndex("Coins1HPerArea")
                        .IsDescending();

                    b.HasIndex("Coins24H")
                        .IsDescending();

                    b.HasIndex("Coins24HPerArea")
                        .IsDescending();

                    b.HasIndex("CoinsPerArea")
                        .IsDescending();

                    b.HasIndex("Food")
                        .IsDescending();

                    b.HasIndex("Food1H")
                        .IsDescending();

                    b.HasIndex("Food1HPerArea")
                        .IsDescending();

                    b.HasIndex("Food24H")
                        .IsDescending();

                    b.HasIndex("Food24HPerArea")
                        .IsDescending();

                    b.HasIndex("FoodPerArea")
                        .IsDescending();

                    b.HasIndex("Goods")
                        .IsDescending();

                    b.HasIndex("Goods1H")
                        .IsDescending();

                    b.HasIndex("Goods1HPerArea")
                        .IsDescending();

                    b.HasIndex("Goods24H")
                        .IsDescending();

                    b.HasIndex("Goods24HPerArea")
                        .IsDescending();

                    b.HasIndex("GoodsPerArea")
                        .IsDescending();

                    b.HasIndex("HasPremiumCultureBuildings");

                    b.HasIndex("HasPremiumFarmBuildings");

                    b.HasIndex("HasPremiumHomeBuildings");

                    b.HasIndex("OpenedExpansionsHash");

                    b.HasIndex("TotalArea");

                    b.HasIndex("CityId", "AgeId");

                    b.HasIndex("PlayerId", "CityId", "CollectedAt")
                        .IsUnique();

                    b.ToTable("player_city_snapshots", (string)null);
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.PlayerCitySnapshotDataEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("PlayerCitySnapshotId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerCitySnapshotId")
                        .IsUnique();

                    b.ToTable("player_city_snapshot_data", (string)null);
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.PlayerNameHistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "Name");

                    b.ToTable("player_name_history_entries", (string)null);
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.PlayerRanking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("CollectedAt")
                        .HasColumnType("date");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CollectedAt")
                        .IsDescending();

                    b.HasIndex("Type", "CollectedAt");

                    b.HasIndex("PlayerId", "Type", "CollectedAt");

                    b.ToTable("player_rankings", (string)null);
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.ProfileSquadDataEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProfileSquadId")
                        .HasColumnType("int");

                    b.Property<byte[]>("SerializedHero")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("SerializedSupportUnit")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileSquadId")
                        .IsUnique();

                    b.ToTable("profile_squad_data", (string)null);
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.ProfileSquadEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AbilityLevel")
                        .HasColumnType("int");

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AscensionLevel")
                        .HasColumnType("int");

                    b.Property<int>("AwakeningLevel")
                        .HasColumnType("int");

                    b.Property<DateOnly>("CollectedAt")
                        .HasColumnType("date");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("UnitId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Age");

                    b.HasIndex("CollectedAt")
                        .IsDescending();

                    b.HasIndex("Level");

                    b.HasIndex("UnitId");

                    b.HasIndex("PlayerId", "UnitId", "CollectedAt")
                        .IsUnique();

                    b.ToTable("profile_squads", (string)null);
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.PvpBattle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("InGameBattleId")
                        .IsRequired()
                        .HasColumnType("varbinary(900)");

                    b.Property<int>("LoserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WinnerId")
                        .HasColumnType("int");

                    b.Property<string>("WorldId")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.HasKey("Id");

                    b.HasIndex("InGameBattleId");

                    b.HasIndex("LoserId");

                    b.HasIndex("PerformedAt")
                        .IsDescending();

                    b.HasIndex("WinnerId");

                    b.HasIndex("WorldId", "InGameBattleId")
                        .IsUnique();

                    b.ToTable("pvp_battles", null, t =>
                        {
                            t.HasCheckConstraint("CK_pvp_battles_WinnerId_LoserId_Different", "[WinnerId] <> [LoserId]");
                        });
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.PvpBattleTeams", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("LoserTeam")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("PvpBattleId")
                        .HasColumnType("int");

                    b.Property<byte[]>("WinnerTeam")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("PvpBattleId")
                        .IsUnique();

                    b.ToTable("pvp_battle_teams", (string)null);
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.PvpRanking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CollectedAt")
                        .IsDescending();

                    b.HasIndex("PlayerId");

                    b.ToTable("pvp_rankings", (string)null);
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.PvpRanking2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("CollectedAt")
                        .HasColumnType("date");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Tier")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CollectedAt")
                        .IsDescending();

                    b.HasIndex("PlayerId");

                    b.ToTable("pvp_rankings2", (string)null);
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.RelicInsightsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FromLevel")
                        .HasColumnType("int");

                    b.Property<string>("Relics")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToLevel")
                        .HasColumnType("int");

                    b.Property<string>("UnitId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FromLevel");

                    b.HasIndex("ToLevel");

                    b.HasIndex("UnitId");

                    b.HasIndex("UnitId", "FromLevel", "ToLevel")
                        .IsUnique();

                    b.ToTable("relic_insights", (string)null);
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.SharedSubmissionIdEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SharedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("SharedId")
                        .IsUnique();

                    b.HasIndex("SubmissionId");

                    b.ToTable("shared_submission_ids", (string)null);
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.TopHeroInsightsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int?>("FromLevel")
                        .HasColumnType("int");

                    b.Property<string>("Heroes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ToLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgeId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FromLevel");

                    b.HasIndex("Mode");

                    b.HasIndex("ToLevel");

                    b.ToTable("top_hero_insights", (string)null);
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.UnitBattleStatsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Attack")
                        .HasColumnType("real");

                    b.Property<float>("Defense")
                        .HasColumnType("real");

                    b.Property<float>("Heal")
                        .HasColumnType("real");

                    b.Property<string>("UnitId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("unit_battle_stats", (string)null);
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.WoaPlayerStatsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContributionPoints")
                        .HasColumnType("int");

                    b.Property<DateTime>("ContributionPointsGainedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HealingDone")
                        .HasColumnType("int");

                    b.Property<int>("InGameEventId")
                        .HasColumnType("int");

                    b.Property<int>("LostAttacks")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("RepairsStarted")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VictoryPoints")
                        .HasColumnType("int");

                    b.Property<int>("WonAttacks")
                        .HasColumnType("int");

                    b.Property<int>("WonDefenses")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "InGameEventId")
                        .IsUnique();

                    b.ToTable("woa_player_stats", (string)null);
                });

            modelBuilder.Entity("AlliancePlayer", b =>
                {
                    b.HasOne("Ingweland.Fog.Models.Fog.Entities.Alliance", null)
                        .WithMany()
                        .HasForeignKey("AllianceHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ingweland.Fog.Models.Fog.Entities.Player", null)
                        .WithMany()
                        .HasForeignKey("MemberHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BattleSummaryEntityBattleUnitEntity", b =>
                {
                    b.HasOne("Ingweland.Fog.Models.Fog.Entities.BattleSummaryEntity", null)
                        .WithMany()
                        .HasForeignKey("BattlesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ingweland.Fog.Models.Fog.Entities.BattleUnitEntity", null)
                        .WithMany()
                        .HasForeignKey("UnitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.AllianceAthRanking", b =>
                {
                    b.HasOne("Ingweland.Fog.Models.Fog.Entities.Alliance", null)
                        .WithMany("AthRankings")
                        .HasForeignKey("AllianceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.AllianceMemberEntity", b =>
                {
                    b.HasOne("Ingweland.Fog.Models.Fog.Entities.Alliance", "Alliance")
                        .WithMany("Members")
                        .HasForeignKey("AllianceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ingweland.Fog.Models.Fog.Entities.Player", "Player")
                        .WithOne("AllianceMembership")
                        .HasForeignKey("Ingweland.Fog.Models.Fog.Entities.AllianceMemberEntity", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alliance");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.AllianceNameHistoryEntry", b =>
                {
                    b.HasOne("Ingweland.Fog.Models.Fog.Entities.Alliance", null)
                        .WithMany("NameHistory")
                        .HasForeignKey("AllianceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.AllianceRanking", b =>
                {
                    b.HasOne("Ingweland.Fog.Models.Fog.Entities.Alliance", null)
                        .WithMany("Rankings")
                        .HasForeignKey("AllianceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.AllianceWoaRanking", b =>
                {
                    b.HasOne("Ingweland.Fog.Models.Fog.Entities.Alliance", null)
                        .WithMany("WoaRankings")
                        .HasForeignKey("AllianceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.BattleSquadStatsEntity", b =>
                {
                    b.HasOne("Ingweland.Fog.Models.Fog.Entities.BattleStatsEntity", null)
                        .WithMany("Squads")
                        .HasForeignKey("BattleStatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ingweland.Fog.Models.Fog.Entities.UnitBattleStatsEntity", "Hero")
                        .WithMany()
                        .HasForeignKey("HeroId");

                    b.HasOne("Ingweland.Fog.Models.Fog.Entities.UnitBattleStatsEntity", "SupportUnit")
                        .WithMany()
                        .HasForeignKey("SupportUnitId");

                    b.Navigation("Hero");

                    b.Navigation("SupportUnit");
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.BattleSquadsEntity", b =>
                {
                    b.HasOne("Ingweland.Fog.Models.Fog.Entities.BattleSummaryEntity", null)
                        .WithMany("Squads")
                        .HasForeignKey("BattleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.EventCitySnapshot", b =>
                {
                    b.HasOne("Ingweland.Fog.Models.Fog.Entities.InGameEventEntity", "InGameEvent")
                        .WithMany()
                        .HasForeignKey("InGameEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ingweland.Fog.Models.Fog.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InGameEvent");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.EventCitySnapshotDataEntity", b =>
                {
                    b.HasOne("Ingweland.Fog.Models.Fog.Entities.EventCitySnapshot", "EventCitySnapshot")
                        .WithOne("Data")
                        .HasForeignKey("Ingweland.Fog.Models.Fog.Entities.EventCitySnapshotDataEntity", "EventCitySnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventCitySnapshot");
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.EventCityStrategy", b =>
                {
                    b.HasOne("Ingweland.Fog.Models.Fog.Entities.InGameEventEntity", "InGameEvent")
                        .WithMany()
                        .HasForeignKey("InGameEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ingweland.Fog.Models.Fog.Entities.Player", "Player")
                        .WithMany("EventCityStrategies")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InGameEvent");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.EventCityStrategyDataEntity", b =>
                {
                    b.HasOne("Ingweland.Fog.Models.Fog.Entities.EventCityStrategy", "EventCityStrategy")
                        .WithOne("Data")
                        .HasForeignKey("Ingweland.Fog.Models.Fog.Entities.EventCityStrategyDataEntity", "EventCityStrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventCityStrategy");
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.EventCityWonderRanking", b =>
                {
                    b.HasOne("Ingweland.Fog.Models.Fog.Entities.Player", null)
                        .WithMany("EventCityWonderRankings")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.PlayerAgeHistoryEntry", b =>
                {
                    b.HasOne("Ingweland.Fog.Models.Fog.Entities.Player", null)
                        .WithMany("AgeHistory")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.PlayerAthRanking", b =>
                {
                    b.HasOne("Ingweland.Fog.Models.Fog.Entities.Player", null)
                        .WithMany("AthRankings")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.PlayerCitySnapshot", b =>
                {
                    b.HasOne("Ingweland.Fog.Models.Fog.Entities.Player", "Player")
                        .WithMany("CitySnapshots")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.PlayerCitySnapshotDataEntity", b =>
                {
                    b.HasOne("Ingweland.Fog.Models.Fog.Entities.PlayerCitySnapshot", "PlayerCitySnapshot")
                        .WithOne("Data")
                        .HasForeignKey("Ingweland.Fog.Models.Fog.Entities.PlayerCitySnapshotDataEntity", "PlayerCitySnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerCitySnapshot");
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.PlayerNameHistoryEntry", b =>
                {
                    b.HasOne("Ingweland.Fog.Models.Fog.Entities.Player", null)
                        .WithMany("NameHistory")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.PlayerRanking", b =>
                {
                    b.HasOne("Ingweland.Fog.Models.Fog.Entities.Player", "Player")
                        .WithMany("Rankings")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.ProfileSquadDataEntity", b =>
                {
                    b.HasOne("Ingweland.Fog.Models.Fog.Entities.ProfileSquadEntity", "ProfileSquad")
                        .WithOne("Data")
                        .HasForeignKey("Ingweland.Fog.Models.Fog.Entities.ProfileSquadDataEntity", "ProfileSquadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProfileSquad");
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.ProfileSquadEntity", b =>
                {
                    b.HasOne("Ingweland.Fog.Models.Fog.Entities.Player", "Player")
                        .WithMany("Squads")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.PvpBattle", b =>
                {
                    b.HasOne("Ingweland.Fog.Models.Fog.Entities.Player", "Loser")
                        .WithMany("PvpLosses")
                        .HasForeignKey("LoserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ingweland.Fog.Models.Fog.Entities.Player", "Winner")
                        .WithMany("PvpWins")
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Loser");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.PvpBattleTeams", b =>
                {
                    b.HasOne("Ingweland.Fog.Models.Fog.Entities.PvpBattle", "PvpBattle")
                        .WithOne("Teams")
                        .HasForeignKey("Ingweland.Fog.Models.Fog.Entities.PvpBattleTeams", "PvpBattleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PvpBattle");
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.PvpRanking", b =>
                {
                    b.HasOne("Ingweland.Fog.Models.Fog.Entities.Player", null)
                        .WithMany("PvpRankings")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.PvpRanking2", b =>
                {
                    b.HasOne("Ingweland.Fog.Models.Fog.Entities.Player", null)
                        .WithMany("PvpRankings2")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.WoaPlayerStatsEntity", b =>
                {
                    b.HasOne("Ingweland.Fog.Models.Fog.Entities.Player", null)
                        .WithMany("WoaStats")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.Alliance", b =>
                {
                    b.Navigation("AthRankings");

                    b.Navigation("Members");

                    b.Navigation("NameHistory");

                    b.Navigation("Rankings");

                    b.Navigation("WoaRankings");
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.BattleStatsEntity", b =>
                {
                    b.Navigation("Squads");
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.BattleSummaryEntity", b =>
                {
                    b.Navigation("Squads");
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.EventCitySnapshot", b =>
                {
                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.EventCityStrategy", b =>
                {
                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.Player", b =>
                {
                    b.Navigation("AgeHistory");

                    b.Navigation("AllianceMembership");

                    b.Navigation("AthRankings");

                    b.Navigation("CitySnapshots");

                    b.Navigation("EventCityStrategies");

                    b.Navigation("EventCityWonderRankings");

                    b.Navigation("NameHistory");

                    b.Navigation("PvpLosses");

                    b.Navigation("PvpRankings");

                    b.Navigation("PvpRankings2");

                    b.Navigation("PvpWins");

                    b.Navigation("Rankings");

                    b.Navigation("Squads");

                    b.Navigation("WoaStats");
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.PlayerCitySnapshot", b =>
                {
                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.ProfileSquadEntity", b =>
                {
                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("Ingweland.Fog.Models.Fog.Entities.PvpBattle", b =>
                {
                    b.Navigation("Teams")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
