syntax = "proto3";
import "stat_boost_dto.proto";
import "equipment_item.proto";
import "google/protobuf/any.proto";
import "fixed_point_dto.proto";

option csharp_namespace = "Ingweland.Fog.Inn.Models.Hoh";

message BattleSquadDto {
  int32 battlefield_slot = 1;
  BattleUnitDto hero = 2;
  BattleUnitDto unit = 3;
}

message BattleUnitDto {
  BattleUnitPropertiesDto properties = 1;
  BattleUnitStateDto unit_state = 2;
}

message BattleUnitPropertiesDto {
  reserved 5;
  string unit_id = 1;
  int32 level = 2;
  int32 ascension_level = 3;
  repeated string abilities = 4;
  repeated StatBoostDto stat_boosts = 6;
  //AllEquipmentUnitDataDTO, RelicUnitDataDTO
  repeated google.protobuf.Any domain_data = 7;
  int32 ability_level = 9;
  int32 awakening_level = 10;
  map<string, FixedPointDTO> unit_stats_overrides = 12;
}

message BattleUnitStateDto {
  reserved 2;
  int32 in_battle_id = 1;
  map<string, FixedPointDTO> unit_stats = 3;
}

message AllEquipmentUnitDataDTO {
  repeated SquadEquipmentItemDto items = 1;
}

message SquadEquipmentItemDto {
  string equipmentSlotTypeDefinitionId = 1;
  string equipmentSetDefinitionId = 2;
  string equipmentRarityDefinitionId = 3;
  int32 level = 4;
  EquipmentAttributeDto mainAttribute = 5;
  repeated EquipmentAttributeDto subAttributes = 6;
}

message RelicUnitDataDTO {
  string definition_id = 1;
  int32 level = 2;
  int32 ascension_level = 3;
  string age = 4;
}
