syntax = "proto3";
import "player_dto.proto";
import "alliance_dto.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/wrappers.proto";
import "battle_squad_dto.proto";

option csharp_namespace = "Ingweland.Fog.Inn.Models.Hoh";

message PvpBattleHistoryResponse {
  repeated PvpBattleHistoryEntryDTO history = 1;
  map<int32, AllianceDto> alliance_by_player_id = 2;
}

message PvpBattleHistoryEntryDTO {
  message StageResultDTO {
    repeated BattleSquadDto player_units = 2;
    repeated BattleSquadDto enemy_units = 3;
    google.protobuf.BytesValue battle_id = 4;
    bool won = 5;
    int32 point_change = 6;
  }

  PlayerDto attacker = 1;
  PlayerDto target = 2;
  int32 points_before = 3;
  int32 points_change = 4;
  int32 enemy_points = 5;
  google.protobuf.Timestamp battle_ended = 9;
  bool revenge_used = 12;
  bool revenge_battle = 13;
  repeated StageResultDTO stage_results = 14;
}

